### ISSUE TITLE
BUG: Speech Highlight does not work in some documents

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/nlp#11]
In some documents, it seems ti does not work. In those cases, I get this in the console

<img width="1025" alt="Screenshot 2021-12-23 01 07 57" src="https://user-images.githubusercontent.com/73286100/147168745-eb8ea27b-eaaf-4183-91e1-da5948b97dcd.png">

**Comment by SkepticMystic** [comment]
Interesting... I think I know what might be causing it. Thanks for the report

**Comment by SkepticMystic** [comment]
Can you please send an example of a note that doesn't work. I suspect it happens when a note has brackets with nothing in between. Or perhaps with ellips, they might get treated as periods with nothing between...

**Comment by chrisgrieser** [comment]
sure, here is the note in question
[_The Concept of Technological Interdependence.md](https://github.com/SkepticMystic/nlp/files/7769228/_The.Concept.of.Technological.Interdependence.md)

**Comment by SkepticMystic** [comment]
@chrisgrieser this should also be resolved in 0.1.2 :)

**Comment by chrisgrieser** [comment]
Thanks, works now! 

<img width="1078" alt="Screenshot 2022-01-02 18 32 44" src="https://user-images.githubusercontent.com/73286100/147884257-21c35e70-416a-4170-af5f-e501898e0641.png">
