### ISSUE TITLE
FR: CSS class for every sentence

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/nlp#12]
adding a css class to every sentence as well would also be useful.

This would enable e.g. `.Sentence:nth-child(even)` to apply alternating highlighting etc.

**Comment by SkepticMystic** [comment]
@chrisgrieser this now works in 0.1.0 :)
There is a separate command for `Highlight Sentences`. I don't think CM6 likes having nested decorations, so I can't mark a part of speech inside a sentence, or wrap a sentence span around a PoS span.
So they are separate for now

**Comment by chrisgrieser** [comment]
great! 🤩

**Comment by chrisgrieser** [comment]
Mmmh, I tried it out on some random online article and it does not. 🙁  Here is the note and the console log:
[Lorem Note.md](https://github.com/SkepticMystic/nlp/files/7799270/Lorem.Note.md)
[obsidian.md-1641136740660.log](https://github.com/SkepticMystic/nlp/files/7799271/obsidian.md-1641136740660.log)

**Comment by SkepticMystic** [comment]
Can you give it a try on 0.1.1. I'm still not sure what the bug is exactly, but I managed to get it working on the example you sent
