### ISSUE TITLE
Cryptic abbreviations

### ISSUE THREAD

**Issue by claremacrae** [SkepticMystic/nlp#2]
Who are the target users of this plugin? It sounds interesting and like it might be useful to many...

So I'm wondering how many people will understand what `PoS` is in `Highlight PoS`?

In general, I've found it's good to try to avoid abbreviations, where words can be spelled out in full - and the feature/writing may then be accessible to a wider audience.

Might `Highlight Parts of Speech` work just as well?

**Comment by SkepticMystic** [comment]
Thanks Clare! I agree, I've changed it per your suggestion :)
